FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o downloader ./cmd/downloader

FROM alpine:latest
WORKDIR /app

# Установка минимальных зависимостей
RUN apk add --no-cache python3 ffmpeg py3-pip && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir yt-dlp

# Добавляем в PATH бинарники из виртуального окружения
ENV PATH="/opt/venv/bin:$PATH"

# Копируем скомпилированный бинарник
COPY --from=builder /app/downloader .

# Если нужен .env файл
COPY .env .

EXPOSE 50051
CMD ["./downloader"]