# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import downloader_pb2 as downloader__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in downloader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DownloaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadVideo = channel.unary_unary(
                '/downloader.Downloader/DownloadVideo',
                request_serializer=downloader__pb2.DownloadRequest.SerializeToString,
                response_deserializer=downloader__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.DownloadAudio = channel.unary_unary(
                '/downloader.Downloader/DownloadAudio',
                request_serializer=downloader__pb2.DownloadRequest.SerializeToString,
                response_deserializer=downloader__pb2.DownloadResponse.FromString,
                _registered_method=True)


class DownloaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DownloadVideo(self, request, context):
        """Методы для загрузки медиа
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DownloaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadVideo,
                    request_deserializer=downloader__pb2.DownloadRequest.FromString,
                    response_serializer=downloader__pb2.DownloadResponse.SerializeToString,
            ),
            'DownloadAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadAudio,
                    request_deserializer=downloader__pb2.DownloadRequest.FromString,
                    response_serializer=downloader__pb2.DownloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'downloader.Downloader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('downloader.Downloader', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Downloader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DownloadVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/downloader.Downloader/DownloadVideo',
            downloader__pb2.DownloadRequest.SerializeToString,
            downloader__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/downloader.Downloader/DownloadAudio',
            downloader__pb2.DownloadRequest.SerializeToString,
            downloader__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
