# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: downloader.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'downloader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ownloader.proto\x12\ndownloader\"e\n\x0f\x44ownloadRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07quality\x18\x02 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x03 \x01(\t\x12\x12\n\nmessage_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\"G\n\x10\x44ownloadResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x03\x32\xa4\x01\n\nDownloader\x12J\n\rDownloadVideo\x12\x1b.downloader.DownloadRequest\x1a\x1c.downloader.DownloadResponse\x12J\n\rDownloadAudio\x12\x1b.downloader.DownloadRequest\x1a\x1c.downloader.DownloadResponseB\"Z Go_Yt_Downloader_bot/internal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'downloader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z Go_Yt_Downloader_bot/internal/pb'
  _globals['_DOWNLOADREQUEST']._serialized_start=32
  _globals['_DOWNLOADREQUEST']._serialized_end=133
  _globals['_DOWNLOADRESPONSE']._serialized_start=135
  _globals['_DOWNLOADRESPONSE']._serialized_end=206
  _globals['_DOWNLOADER']._serialized_start=209
  _globals['_DOWNLOADER']._serialized_end=373
# @@protoc_insertion_point(module_scope)
